### ISSUE TITLE
I can't run CLI

### ISSUE THREAD

**Issue by rickyrauch** [joshblack/react-svg-converter#9]
Hi!

I love this module, I'd like to run the cli but I'm getting this error: 

Command: `react-svg-converter -i SVG/ -o JSX/ -t reactDefault `

```
Error: Cannot find module '../lib'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-svg-converter/bin/index.js:6:34)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by 8ctopotamus** [comment]
I am having the same issue with the cli. Is there any fix?

**Comment by scf4** [comment]
Same, I'm trying this instead https://medium.com/@scbarrus/transform-raw-svg-files-into-react-components-in-seconds-25faf56a6f07

**Comment by zeroasterisk** [comment]
```
$ react-svg-converter -i icon-or-128.svg -o icon-or.js
module.js:487
    throw err;
    ^

Error: Cannot find module '../lib'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/alan/.nvm/versions/node/v8.1.2/lib/node_modules/react-svg-converter/bin/index.js:6:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
